site_name: 'your documentation site name'
site_description: 'a brief description'
#uncomment the below lines if you want to enable the edit button in your techdocs
#edit_uri: blob/main/docs/ #don't change it, just uncomment
#repo_url: '<insert your repo url here>'
theme:
  name: material
  palette:
    scheme: default
  features:
    - toc.follow
    - toc.integrate
plugins:
  - techdocs-core
